import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../database_key.dart';

/// Android, and any other platform with a real file system.
///
/// This is the one the product actually ships on. The database is a file
/// opened through SQLCipher, keyed from the platform credential store.
///
/// `PRAGMA key` has to be the first statement executed on the connection,
/// which is exactly what drift's `setup` callback is for. The SQLCipher build
/// itself is selected in pubspec.yaml under `hooks: user_defines: sqlite3:
/// source: sqlcipher`, so no separate native package is involved.
///
/// This runs on the same isolate as the UI rather than through
/// `createInBackground`. For a roster of a few hundred households the
/// difference is not measurable, and a single isolate is far easier to reason
/// about. If a screen ever does start to stutter, that is the thing to
/// change, and it is a change in this one function.
QueryExecutor openBillAlertDatabase() {
  return LazyDatabase(() async {
    final directory = await getApplicationDocumentsDirectory();
    final file = File(p.join(directory.path, 'billalert_cache.db'));
    final key = await DatabaseKey.readOrCreate();

    return NativeDatabase(
      file,
      setup: (db) {
        // A PRAGMA cannot take a bound parameter, so the key is interpolated.
        // It is generated by us and base64, but the quotes are doubled anyway
        // rather than relying on that.
        final escaped = key.replaceAll("'", "''");
        db.execute("pragma key = '$escaped';");
        db.execute('pragma foreign_keys = on;');
      },
    );
  });
}

/// SYS-05 holds here: the file on disk is unreadable without the key.
const bool databaseIsEncrypted = true;
